M2Link/Entities/Message.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace M2Link.Entities
{
    public class Message : Entity
    {
        public string Content { get; set; }
        public Guid UserId { get; set; }

        public virtual User User { get; set; }
    }
}

M2Link/Models/Message/MessageModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace M2Link.Models
{
    public class MessageModel
    {
        public Guid UserId { get; set; }

        [DisplayName("Pseudo")]
        public string Pseudo { get; set; }

        [Required]
        [DisplayName("Contenu")]
        public string Content { get; set; }

        [DisplayName("Date de création")]
        public DateTime CreateAt { get; set; }

        public MessageModel() { }
        public MessageModel(Entities.Message message)
        {
            UserId = message.UserId;
            Pseudo = message.User.Pseudo;
            Content = message.Content;
            CreateAt = message.CreatedAt;
        }
    }
}

M2Link/Models/Message/MessagesModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace M2Link.Models.Message
{
    public class MessagesModel
    {
        [DisplayName("Nouveau Message")]
        public MessageModel NewMessage { get; set; }

        [DisplayName("Messages")]
        public List<MessageModel> Messages { get; set; }
    }
}

M2Link/Controllers/MessageController.cs
using M2Link.Context;
using M2Link.Entities;
using M2Link.Models;
using M2Link.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace M2Link.Controllers
{
    [Authorize]
    public class MessageController : Controller
    {
        // GET: Create
        [HttpGet]
        public ActionResult Create()
        {
            MessageModel model = new MessageModel();

            return View(model);
        }

        // POST: Create
        [HttpPost]
        public ActionResult Create(MessageModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            using (var context = new M2LinkContext())
            {
                var user = new UserRepository(context).GetAll().FirstOrDefault(u => u.Id.ToString() == User.Identity.Name);
                user.Messages.Add(new Message()
                {
                    Content = model.Content,
                    UserId = Guid.Parse(User.Identity.Name),
                    CreatedAt = DateTime.Now
                });
                context.SaveChanges();
            }

            return RedirectToAction("Index", "Home");
        }
    }
}

M2Link/Controllers/RegisterController.cs
using M2Link.Context;
using M2Link.Entities;
using M2Link.Models;
using M2Link.Repositories;
using Microsoft.AspNetCore.Cryptography.KeyDerivation;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Web;
using System.Web.Mvc;

namespace M2Link.Controllers
{
    public class RegisterController : Controller
    {
        // GET: Register
        [HttpGet]
        public ActionResult Form()
        {
            RegisterModel model = new RegisterModel();

            return View(model);
        }

        // POST: Register
        [HttpPost]
        public ActionResult Form(RegisterModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            using (var context = new M2LinkContext())
            {
                byte[] data = System.Text.Encoding.ASCII.GetBytes(model.Password);
                String hashed = Convert.ToBase64String(SHA384.Create().ComputeHash(data));

                byte[] imageData = null;
                if (Request.Files.Count > 0)
                {
                    HttpPostedFileBase poImgFile = Request.Files[0];

                    using (var binary = new BinaryReader(poImgFile.InputStream))
                    {
                        imageData = binary.ReadBytes(poImgFile.ContentLength);
                    }
                }

                new UserRepository(context).Add(new User()
                {
                    FirstName = model.FirstName,
                    LastName = model.LastName,
                    Email = model.Email,
                    Pseudo = model.Pseudo,
                    Password = hashed,
                    Avatar = imageData
                });


                context.SaveChanges();
            }
            
            return RedirectToAction("Index", "Home");
        }
    }
}

M2Link/Controllers/UserController.cs
using M2Link.Context;
using M2Link.Entities;
using M2Link.Models;
using M2Link.Repositories;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace M2Link.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        [HttpGet]
        public ActionResult Index()
        {
            using (var context = new M2LinkContext())
            {
                return View(new UsersModel(new UserRepository(context).GetAll(),
                    new UserRepository(context).GetAll().FirstOrDefault(u => u.Id.ToString() == User.Identity.Name)));
            }
        }

        // GET: Login
        [HttpGet]
        [AllowAnonymous]
        public ActionResult Login()
        {
            LoginModel model = new LoginModel();

            return View(model);
        }

        // POST: Login
        [HttpPost]
        [AllowAnonymous]
        public ActionResult Login(LoginModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            using (var context = new M2LinkContext())
            {
                byte[] data = System.Text.Encoding.ASCII.GetBytes(model.Password);
                String hashed = Convert.ToBase64String(SHA384.Create().ComputeHash(data));

                var user = new UserRepository(context).GetUser(model.Pseudo);
                if (user == null)
                {
                    ModelState.AddModelError("ErrorPseudo", "Ce pseudo n'existe pas");
                }
                else if (user.Password != hashed)
                {
                    ModelState.AddModelError("ErrorPassword", "Mot de passe incorrect");
                }
                else
                {
                    // Connexion
                    FormsAuthentication.SetAuthCookie(user.Id.ToString(), true);
                    return RedirectToAction("Index", "Home");
                }
            }
            return View(model);
        }

        // POST: Logout
        [HttpPost]
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Login");
        }

        // GET: Edit
        [HttpGet]
        public ActionResult Edit()
        {
            var user = new User();
            using (var context = new M2LinkContext())
            {
                user = new UserRepository(context).GetAll().FirstOrDefault(u => u.Id.ToString() == User.Identity.Name);
            }
            return View(new EditUserModel(user));
        }

        // POST: Edit
        [HttpPost]
        public ActionResult Edit(EditUserModel model)
        {

            if (!ModelState.IsValid)
                return View(model);

            byte[] data = System.Text.Encoding.ASCII.GetBytes(model.Password);
            String hashed = Convert.ToBase64String(SHA384.Create().ComputeHash(data));

            model.Password = hashed;

            byte[] imageData = null;
            if (Request.Files.Count > 0)
            {
                HttpPostedFileBase poImgFile = Request.Files[0];
                using (var binary = new BinaryReader(poImgFile.InputStream))
                {
                    imageData = binary.ReadBytes(poImgFile.ContentLength);
                }
                model.Avatar = imageData;
            }

            using (var context = new M2LinkContext())
            {
                new UserRepository(context).EditUser(Guid.Parse(User.Identity.Name), model);
                context.SaveChanges();
            }
            
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public ActionResult Details(string id)
        {
            UserModel userModel = null;
            using (var context = new M2LinkContext())
            {
                var loggedUser = new UserRepository(context).GetAll().FirstOrDefault(u => u.Id.ToString() == User.Identity.Name);
                var user = new UserRepository(context).GetAll().FirstOrDefault(u => u.Id.ToString() == id);
                bool? IsFollowed;
                if (user == loggedUser)
                {
                    IsFollowed = null;
                }
                else
                {
                    IsFollowed = loggedUser.Followers.Contains(user);
                }
                userModel = new UserModel(new UserRepository(context).GetAll().FirstOrDefault(u => u.Id.ToString() == id), IsFollowed);
            }
            return View(userModel);
        }

        [HttpPost]
        public ActionResult Description(string description)
        {
            using (var context = new M2LinkContext())
            {
                var loggedUser = new UserRepository(context).GetAll().FirstOrDefault(u => u.Id.ToString() == User.Identity.Name);
                loggedUser.Description = description;
                context.SaveChanges();
            }
            return RedirectToAction("Index", "Home");

        }

        [HttpPost]
        public JsonResult Follow(string id)
        {
            using (var context = new M2LinkContext())
            {
                
                if (new UserRepository(context).Follow(Guid.Parse(User.Identity.Name), Guid.Parse(id)))
                {
                    context.SaveChanges();
                    return Json("Vous suivez maintenant : " 
                        + new UserRepository(context).GetAll()
                        .FirstOrDefault(u => u.Id == Guid.Parse(id)).Pseudo);
                }
            }
            return Json("Erreur");
        }

        [HttpPost]
        public JsonResult Unfollow(string id)
        {
            using (var context = new M2LinkContext())
            {
                if (new UserRepository(context).Unfollow(Guid.Parse(User.Identity.Name), Guid.Parse(id)))
                {
                    context.SaveChanges();
                    return Json("Vous ne suivez plus : "
                        + new UserRepository(context).GetAll()
                        .FirstOrDefault(u => u.Id == Guid.Parse(id)).Pseudo);
                }
            }
            return Json("Erreur");
        }

        public FileContentResult Photo(string pseudo)
        {
            using (var context = new M2LinkContext())
            {
                var user = context.Users.Where(x => x.Pseudo == pseudo).FirstOrDefault();
                if (user.Avatar == null)
                {
                    string fileName = HttpContext.Server.MapPath(@"~/Images/default.png");
                    byte[] imageData = null;
                    FileInfo fileInfo = new FileInfo(fileName);
                    long imageFileLength = fileInfo.Length;
                    FileStream fs = new FileStream(fileName, FileMode.Open, FileAccess.Read);
                    BinaryReader br = new BinaryReader(fs);
                    imageData = br.ReadBytes((int)imageFileLength);
                    return new FileContentResult(imageData, "image/png");
                }
                return new FileContentResult(user.Avatar, "image/png");
            }
        }
    }
}

M2Link/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mon application ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/fontawesome")
    @Scripts.Render("~/bundles/modernizr")
    <link href="@Url.Content("~/Content/css/navbar.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/Content/css/message.css")" rel="stylesheet" type="text/css" />


</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Le .NETWork", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse navbar-dark indigo">
                @if (!Context.User.Identity.IsAuthenticated)
                {
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <a href="@Url.Action("Form", "Register")">
                                <span class="glyphicon glyphicon-registration-mark"></span>
                                S'inscrire
                            </a>
                        </li>
                        <li>
                            <a href="@Url.Action("Login", "User")">
                                <span class="glyphicon glyphicon-log-in"></span>
                                Se connecter
                            </a>
                        </li>
                    </ul>
                }
                else
                {
                    using (Html.BeginForm("Logout", "User", FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
                    {
                        <ul class="nav navbar-nav navbar-right">
                            <li>
                                <a href="@Url.Action("Index", "User")">
                                    <span class="fa fa-users"></span>
                                    Utilisateurs
                                </a>
                            </li>
                            <li>
                                <a href="@Url.Action("Edit", "User")">
                                    <span class="glyphicon glyphicon-user"></span>
                                    Edition
                                </a>
                            </li>
                            <li>
                                <a href="javascript:document.getElementById('logoutForm').submit()">
                                    Se déconnecter
                                    <span class="glyphicon glyphicon-log-out"></span>
                                </a>
                            </li>

                        </ul>
                    }

                }
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Le .NETWork - Martin Blondel, Antoine Guillory</p>
            <a href="@Url.Action("Description", "Description")">
                Une petite description de la webapp ?
            </a>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/toastr")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

M2Link/Views/Shared/_Message.cshtml
@model MessageModel

    <li class="list-group-item message-posted">
        <span onclick="window.location.href = '@Url.Action("Details", "User", new { id = Model.UserId })';">
            <p>
                <img src="@Url.Action("Photo", "User" , new { pseudo=Model.Pseudo })" class="avatar" height="48" width="48" />
                <span class="color-dark">
                    &nbsp;&nbsp;@Model.Pseudo
                </span><span class="createdat">Le @Model.CreateAt</span> à dit
            </p>
            <div>
                @Model.Content
            </div>
        </span>
    </li>

M2Link/Views/Shared/_NewMessage.cshtml
@{
    ViewBag.Title = "Creation de message";
}

@model MessageModel

    <h2>Poster un message</h2>

@using (Html.BeginForm("Create", "Message", FormMethod.Post))
{
    <div class="col-md-12">
        <div class="form-group">
            @Html.LabelFor(m => m.Content)
            @Html.TextAreaFor(m => m.Content, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Content, null, new { @class = "text-danger" })
        </div>
        <button type="submit" class="btn btn-primary" id="checkout">Poster</button>
    </div>
}